SET standard_conforming_strings = OFF;
CREATE SCHEMA "osm2igeo";
DROP TABLE IF EXISTS "osm2igeo"."a_osm_reseau_routier_toponyme_communication" CASCADE;
DELETE FROM geometry_columns WHERE f_table_name = 'a_osm_reseau_routier_toponyme_communication' AND f_table_schema = 'osm2igeo';
BEGIN;
CREATE TABLE "osm2igeo"."a_osm_reseau_routier_toponyme_communication" ( "ogc_fid" SERIAL, CONSTRAINT "a_osm_reseau_routier_toponyme_communication_pk" PRIMARY KEY ("ogc_fid") );
SELECT AddGeometryColumn('osm2igeo','a_osm_reseau_routier_toponyme_communication','geom',2154,'GEOMETRY',2);
CREATE INDEX "a_osm_reseau_routier_toponyme_communication_geom_geom_idx" ON "osm2igeo"."a_osm_reseau_routier_toponyme_communication" USING GIST ("geom");
ALTER TABLE "osm2igeo"."a_osm_reseau_routier_toponyme_communication" ADD COLUMN "id" VARCHAR;
ALTER TABLE "osm2igeo"."a_osm_reseau_routier_toponyme_communication" ADD COLUMN "nom" VARCHAR;
ALTER TABLE "osm2igeo"."a_osm_reseau_routier_toponyme_communication" ADD COLUMN "nature" VARCHAR;
ALTER TABLE "osm2igeo"."a_osm_reseau_routier_toponyme_communication" ADD COLUMN "source" VARCHAR;
ALTER TABLE "osm2igeo"."a_osm_reseau_routier_toponyme_communication" ADD COLUMN "date_maj" VARCHAR;
COMMIT;
