export DATE=$(date '+%y%m')
#Téléchargement des données OSM - Geofabrik
cd "/volume1/docker/gdal/data_in"
################################################################################
rm "./AFRIQUE/MAROC.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/morocco'-'$DATE'01.osm.pbf' > "./AFRIQUE/MAROC.pbf"
rm "./AFRIQUE/ALGERIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/algeria'-'$DATE'01.osm.pbf' > "./AFRIQUE/ALGERIE.pbf"
rm "./AFRIQUE/TUNISIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/tunisia'-'$DATE'01.osm.pbf' > "./AFRIQUE/TUNISIE.pbf"
rm "./AFRIQUE/MAURITANIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/mauritania'-'$DATE'01.osm.pbf' > "./AFRIQUE/MAURITANIE.pbf"
rm "./AFRIQUE/REPUBLIQUE_CENTRAFRICAINE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/central-african-republic'-'$DATE'01.osm.pbf' > "./AFRIQUE/REPUBLIQUE_CENTRAFRICAINE.pbf"
rm "./AFRIQUE/CONGO_RDC.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/congo-democratic-republic'-'$DATE'01.osm.pbf' > "./AFRIQUE/CONGO_RDC.pbf"
rm "./AFRIQUE/GABON.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/gabon'-'$DATE'01.osm.pbf' > "./AFRIQUE/GABON.pbf"
rm "./AFRIQUE/DJIBOUTI.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/djibouti'-'$DATE'01.osm.pbf' > "./AFRIQUE/DJIBOUTI.pbf"
rm "./AFRIQUE/GUINEE_EQUATORIALE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/equatorial-guinea'-'$DATE'01.osm.pbf' > "./AFRIQUE/GUINEE_EQUATORIALE.pbf"
rm "./AFRIQUE/COMORES.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/comores'-'$DATE'01.osm.pbf' > "./AFRIQUE/COMORES.pbf"
rm "./AFRIQUE/SEYCHELLES.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/seychelles'-'$DATE'01.osm.pbf' > "./AFRIQUE/SEYCHELLES.pbf"
rm "./AFRIQUE/CONGO_RC.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/congo-brazzaville'-'$DATE'01.osm.pbf' > "./AFRIQUE/CONGO_RC.pbf"
rm "./AFRIQUE/RWANDA.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/rwanda'-'$DATE'01.osm.pbf' > "./AFRIQUE/RWANDA.pbf"
rm "./AFRIQUE/BURUNDI.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/burundi'-'$DATE'01.osm.pbf' > "./AFRIQUE/BURUNDI.pbf"
rm "./AFRIQUE/GUINEE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/guinea'-'$DATE'01.osm.pbf' > "./AFRIQUE/GUINEE.pbf"
rm "./AFRIQUE/TOGO.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/togo'-'$DATE'01.osm.pbf' > "./AFRIQUE/TOGO.pbf"
rm "./AFRIQUE/BENIN.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/benin'-'$DATE'01.osm.pbf' > "./AFRIQUE/BENIN.pbf"
rm "./AFRIQUE/NIGER.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/niger'-'$DATE'01.osm.pbf' > "./AFRIQUE/NIGER.pbf"
rm "./AFRIQUE/TCHAD.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/chad'-'$DATE'01.osm.pbf' > "./AFRIQUE/TCHAD.pbf"
rm "./AFRIQUE/CAMEROUN.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/cameroon'-'$DATE'01.osm.pbf' > "./AFRIQUE/CAMEROUN.pbf"
rm "./AFRIQUE/MADAGASCAR.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/madagascar'-'$DATE'01.osm.pbf' > "./AFRIQUE/MADAGASCAR.pbf"
rm "./AFRIQUE/BURKINA_FASO.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/burkina-faso'-'$DATE'01.osm.pbf' > "./AFRIQUE/BURKINA_FASO.pbf"
rm "./AFRIQUE/MALI.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/mali'-'$DATE'01.osm.pbf' > "./AFRIQUE/MALI.pbf"
rm "./AFRIQUE/SENEGAL_GAMBIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/senegal-and-gambia'-'$DATE'01.osm.pbf' > "./AFRIQUE/SENEGAL_GAMBIE.pbf"
rm "./AFRIQUE/COTE_D_IVOIRE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/africa/ivory-coast'-'$DATE'01.osm.pbf' > "./AFRIQUE/COTE_D_IVOIRE.pbf"
