export DATE=$(date '+%y%m')
#Téléchargement des données OSM - Geofabrik
cd "/volume1/docker/gdal/data_in"
################################################################################
#FRANCE
rm "./FRANCE/42_ALSACE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/alsace'-'$DATE'01.osm.pbf' > "./FRANCE/42_ALSACE.pbf"
rm "./FRANCE/72_AQUITAINE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/aquitaine'-'$DATE'01.osm.pbf' > "./FRANCE/72_AQUITAINE.pbf"
rm "./FRANCE/83_AUVERGNE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/auvergne'-'$DATE'01.osm.pbf' > "./FRANCE/83_AUVERGNE.pbf"
rm "./FRANCE/25_BASSE_NORMANDIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/basse-normandie'-'$DATE'01.osm.pbf' > "./FRANCE/25_BASSE_NORMANDIE.pbf"
rm "./FRANCE/26_BOURGOGNE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/bourgogne'-'$DATE'01.osm.pbf' > "./FRANCE/26_BOURGOGNE.pbf"
rm "./FRANCE/53_BRETAGNE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/bretagne'-'$DATE'01.osm.pbf' > "./FRANCE/53_BRETAGNE.pbf"
rm "./FRANCE/24_CENTRE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/centre'-'$DATE'01.osm.pbf' > "./FRANCE/24_CENTRE.pbf"
rm "./FRANCE/21_CHAMPAGNE_ARDENNE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/champagne-ardenne'-'$DATE'01.osm.pbf' > "./FRANCE/21_CHAMPAGNE_ARDENNE.pbf"
rm "./FRANCE/94_CORSE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/corse'-'$DATE'01.osm.pbf' > "./FRANCE/94_CORSE.pbf"
rm "./FRANCE/43_FRANCHE_COMTE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/franche-comte'-'$DATE'01.osm.pbf' > "./FRANCE/43_FRANCHE_COMTE.pbf"
rm "./FRANCE/23_HAUTE_NORMANDIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/haute-normandie'-'$DATE'01.osm.pbf' > "./FRANCE/23_HAUTE_NORMANDIE.pbf"
rm "./FRANCE/11_ILE_DE_FRANCE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/ile-de-france'-'$DATE'01.osm.pbf' > "./FRANCE/11_ILE_DE_FRANCE.pbf"
rm "./FRANCE/91_LANGUEDOC_ROUSSILLON.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/languedoc-roussillon'-'$DATE'01.osm.pbf' > "./FRANCE/91_LANGUEDOC_ROUSSILLON.pbf"
rm "./FRANCE/74_LIMOUSIN.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/limousin'-'$DATE'01.osm.pbf' > "./FRANCE/74_LIMOUSIN.pbf"
rm "./FRANCE/41_LORRAINE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/lorraine'-'$DATE'01.osm.pbf' > "./FRANCE/41_LORRAINE.pbf"
rm "./FRANCE/73_MIDI_PYRENEES.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/midi-pyrenees'-'$DATE'01.osm.pbf' > "./FRANCE/73_MIDI_PYRENEES.pbf"
rm "./FRANCE/31_NORD_PAS_DE_CALAIS.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/nord-pas-de-calais'-'$DATE'01.osm.pbf' > "./FRANCE/31_NORD_PAS_DE_CALAIS.pbf"
rm "./FRANCE/52_PAYS_DE_LA_LOIRE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/pays-de-la-loire'-'$DATE'01.osm.pbf' > "./FRANCE/52_PAYS_DE_LA_LOIRE.pbf"
rm "./FRANCE/22_PICARDIE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/picardie'-'$DATE'01.osm.pbf' > "./FRANCE/22_PICARDIE.pbf"
rm "./FRANCE/54_POITOU_CHARENTES.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/poitou-charentes'-'$DATE'01.osm.pbf' > "./FRANCE/54_POITOU_CHARENTES.pbf"
rm "./FRANCE/93_PROVENCE_ALPES_COTE_D_AZUR.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/provence-alpes-cote-d-azur'-'$DATE'01.osm.pbf' > "./FRANCE/93_PROVENCE_ALPES_COTE_D_AZUR.pbf"
rm "./FRANCE/82_RHONE_ALPES.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/rhone-alpes'-'$DATE'01.osm.pbf' > "./FRANCE/82_RHONE_ALPES.pbf"
rm "./DOM_TOM/GUADELOUPE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/guadeloupe'-'$DATE'01.osm.pbf' > "./DOM_TOM/GUADELOUPE.pbf"
rm "./DOM_TOM/MARTINIQUE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/martinique'-'$DATE'01.osm.pbf' > "./DOM_TOM/MARTINIQUE.pbf"
rm "./DOM_TOM/GUYANE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/guyane'-'$DATE'01.osm.pbf' > "./DOM_TOM/GUYANE.pbf"
rm "./DOM_TOM/REUNION.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/reunion'-'$DATE'01.osm.pbf' > "./DOM_TOM/REUNION.pbf"
rm "./DOM_TOM/MAYOTTE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/france/mayotte'-'$DATE'01.osm.pbf' > "./DOM_TOM/MAYOTTE.pbf"
################################################################################
#BELGIQUE
rm "./BELGIQUE/BELGIQUE.pbf"
curl --limit-rate 100K https://download.geofabrik.de/europe/belgium'-'$DATE'01.osm.pbf' > "./BELGIQUE/BELGIQUE.pbf"
