SET standard_conforming_strings = OFF;
CREATE SCHEMA "osm2igeo";
DROP TABLE IF EXISTS "osm2igeo"."d_osm_hydrographie_point_eau" CASCADE;
DELETE FROM geometry_columns WHERE f_table_name = 'd_osm_hydrographie_point_eau' AND f_table_schema = 'osm2igeo';
BEGIN;
CREATE TABLE "osm2igeo"."d_osm_hydrographie_point_eau" ( "ogc_fid" SERIAL, CONSTRAINT "d_osm_hydrographie_point_eau_pk" PRIMARY KEY ("ogc_fid") );
SELECT AddGeometryColumn('osm2igeo','d_osm_hydrographie_point_eau','geom',2154,'GEOMETRY',2);
CREATE INDEX "d_osm_hydrographie_point_eau_geom_geom_idx" ON "osm2igeo"."d_osm_hydrographie_point_eau" USING GIST ("geom");
ALTER TABLE "osm2igeo"."d_osm_hydrographie_point_eau" ADD COLUMN "id" VARCHAR;
ALTER TABLE "osm2igeo"."d_osm_hydrographie_point_eau" ADD COLUMN "nature" VARCHAR;
ALTER TABLE "osm2igeo"."d_osm_hydrographie_point_eau" ADD COLUMN "source" VARCHAR;
ALTER TABLE "osm2igeo"."d_osm_hydrographie_point_eau" ADD COLUMN "date_maj" VARCHAR;
COMMIT;
