set search_path to public ;
\i 'A_OSM_RESEAU_ROUTIER/CHEMIN.sql'
\i 'A_OSM_RESEAU_ROUTIER/ROUTE.sql'
\i 'A_OSM_RESEAU_ROUTIER/SURFACE_ROUTE.sql'
\i 'A_OSM_RESEAU_ROUTIER/TOPONYME_COMMUNICATION.sql'

\i 'B_OSM_VOIES_FERREES_ET_AUTRES/GARE.sql'
\i 'B_OSM_VOIES_FERREES_ET_AUTRES/PASSAGE_A_NIVEAU.sql'
\i 'B_OSM_VOIES_FERREES_ET_AUTRES/TOPONYME_COMMUNICATION.sql'
\i 'B_OSM_VOIES_FERREES_ET_AUTRES/TOPONYME_FERRE.sql'
\i 'B_OSM_VOIES_FERREES_ET_AUTRES/TRONCON_VOIE_FERREE.sql'
\i 'B_OSM_VOIES_FERREES_ET_AUTRES/TELEPHERIQUE.sql'

\i 'C_OSM_TRANSPORT_ENERGIE/EOLIENNE.sql'
\i 'C_OSM_TRANSPORT_ENERGIE/LIGNE_ELECTRIQUE.sql'
\i 'C_OSM_TRANSPORT_ENERGIE/POSTE_TRANSFORMATION.sql'
\i 'C_OSM_TRANSPORT_ENERGIE/PYLONE.sql'

\i 'D_OSM_HYDROGRAPHIE/BARRAGE.sql'
\i 'D_OSM_HYDROGRAPHIE/CANALISATION_EAU.sql'
\i 'D_OSM_HYDROGRAPHIE/POINT_EAU.sql'
\i 'D_OSM_HYDROGRAPHIE/RESERVOIR_EAU.sql'
\i 'D_OSM_HYDROGRAPHIE/SURFACE_EAU.sql'
\i 'D_OSM_HYDROGRAPHIE/TRONCON_COURS_EAU.sql'

\i 'E_OSM_BATI/BATI.sql'
\i 'E_OSM_BATI/CIMETIERE.sql'
\i 'E_OSM_BATI/PISTE_AERODROME.sql'
\i 'E_OSM_BATI/RESERVOIR.sql'
\i 'E_OSM_BATI/TERRAIN_SPORT.sql'

\i 'F_OSM_VEGETATION/ZONE_VEGETATION.sql'

\i 'H_OSM_ADMINISTRATIF/COMMUNE.sql'
\i 'H_OSM_ADMINISTRATIF/CHEF_LIEU.sql'
\i 'H_OSM_ADMINISTRATIF/ARRONDISSEMENT.sql'

\i 'I_OSM_ZONE_ACTIVITE/PAI_ADMINISTRATIF_MILITAIRE.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_CULTURE_LOISIRS.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_ESPACE_NATUREL.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_GESTION_DECHETS.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_GESTION_EAUX.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_HYDROGRAPHIE.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_INDUSTRIEL_COMMERCIAL.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_RELIGIEUX.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_SANTE.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_SCIENCE_ENSEIGNEMENT.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_SPORT.sql'
\i 'I_OSM_ZONE_ACTIVITE/PAI_ZONE_HABITATION.sql'
\i 'I_OSM_ZONE_ACTIVITE/TERRAIN_MILITAIRE.sql'

\i 'T_OSM_TOPONYMES/LIEU_DIT_HABITE.sql'
\i 'T_OSM_TOPONYMES/LIEU_DIT_NON_HABITE.sql'
\i 'T_OSM_TOPONYMES/TOPONYME_DIVERS.sql'

\i 'X_OSM_TOPO/TOPO_POI.sql'
\i 'X_OSM_TOPO/TOPO_RELIEF.sql'

\i 'Y_OSM_ENVIRONNEMENT/AIRE_PROTEGEE.sql'
