SET standard_conforming_strings = OFF;
CREATE SCHEMA "osm2igeo";
DROP TABLE IF EXISTS "osm2igeo"."e_osm_bati_terrain_sport" CASCADE;
DELETE FROM geometry_columns WHERE f_table_name = 'e_osm_bati_terrain_sport' AND f_table_schema = 'osm2igeo';
BEGIN;
CREATE TABLE "osm2igeo"."e_osm_bati_terrain_sport" ( "ogc_fid" SERIAL, CONSTRAINT "e_osm_bati_terrain_sport_pk" PRIMARY KEY ("ogc_fid") );
SELECT AddGeometryColumn('osm2igeo','e_osm_bati_terrain_sport','geom',2154,'GEOMETRY',2);
CREATE INDEX "e_osm_bati_terrain_sport_geom_geom_idx" ON "osm2igeo"."e_osm_bati_terrain_sport" USING GIST ("geom");
ALTER TABLE "osm2igeo"."e_osm_bati_terrain_sport" ADD COLUMN "id" VARCHAR;
ALTER TABLE "osm2igeo"."e_osm_bati_terrain_sport" ADD COLUMN "nature" VARCHAR;
ALTER TABLE "osm2igeo"."e_osm_bati_terrain_sport" ADD COLUMN "sport" VARCHAR;
ALTER TABLE "osm2igeo"."e_osm_bati_terrain_sport" ADD COLUMN "source" VARCHAR;
ALTER TABLE "osm2igeo"."e_osm_bati_terrain_sport" ADD COLUMN "date_maj" VARCHAR;
COMMIT;
